spring:
  application:
    name: practice02
  datasource:
    url: jdbc:h2:mem:practice02
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true